### ISSUE TITLE
Add port to ios

### ISSUE THREAD

**Issue by Juoelenis** [spiridon-alexandru/MobileWii#4]
Tbe title says it all

**Comment by Juoelenis** [comment]
Adu ai support pt iOS ca nu toti au Android

**Comment by spiridon-alexandru** [comment]
Salutare, ma bucur sa vad ca esti interesat de proiectul asta mic, dar din pacate a fost un proiect de hobby acum 12 ani. 

De atunci am trecut de la mobile development la backend si nici daca as vrea nu as putea acum sa il implementez pe iOS (cred ca nu am lucrat pe iOS de mai mult de 12 ani) fara sa invat din nou tot ce s-a schimbat in mediul de dezvoltare iOS.

Cine stie, poate revin catre mobile in viitor sau poate ai chef sa il extinzi tu ca si hobby si sa faci un pull request :)
